### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'?

### ISSUE THREAD

**Issue by 1247862674** [piyushK52/comfy_runner#22]

**Comment by piyushK52** [comment]
please cross-check that you have python3.10 on your machine and the venv is created through the same

**Comment by 1247862674** [comment]
Not supporting python3.12?

**Comment by 1247862674** [comment]
How to get data for more models？

**Comment by piyushK52** [comment]
1. No it doesn’t support python3.12 for now
2. Please check the main.py file for examples of how to pass extra_models_list as an argument (if the models you require are not present inside comfy_runner)

**Comment by 1247862674** [comment]
It seems that it can only support api json. It would be great if it could directly support workflow json! ! !

**Comment by piyushK52** [comment]
yeah agreed, i will try to add normal json support when I get the time. closing this ticket for now.
