### ISSUE TITLE
Civitai下载错误

### ISSUE THREAD

**Issue by sig233** [piyushK52/comfy_runner#7]
INFO:app_logger:Downloading dynavisionXLAllInOneStylized_release0534bakedvae.safetensors
INFO:app_logger:Error generating output HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/download/models/169718 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EF62D60A10>, 'Connection to civitai.com timed out. (connect timeout=None)'))
DEBUG:app_logger:Process 20724 (Port 6969)

链接错误有啥解决方法嘛

**Comment by piyushK52** [comment]
civit timed out the connection on their end... maybe they have added some sort of throttling (or maybe the model link has changed).. try providing the link yourself like this (in the extra_model_list params)
` runner.predict(
     workflow_input="examples/img2img/i2i_workflow_api.json",
     extra_models_list=[
         {
             "filename": "mod_sdxl.safetensors",
             "url": "https://civitai.com/api/download/models/299716",
             "dest": "./ComfyUI/models/checkpoints/"
         }
     ],
     extra_node_urls=["https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"],
     stop_server_after_completion=True
)`

**Comment by sig233** [comment]
ok nvm, I found out the workflow referenced an older version of the model, which civitai might removed from download repo.

I could manually go into the workflow json and download.
